/**
 *
 * @param {*} param0
 * @description This is Constant which keep the naming consistent because all action types are gathered in a single place.
 * @author Ravi Ranjan
 * @returns the constant name
 */

// For Registration
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

// // For Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// For Getting Product list
export const PRODUCTLIST_REQUEST = 'PRODUCTLIST_REQUEST';
export const PRODUCTLIST_SUCCESS = 'PRODUCTLIST_SUCCESS';

//For Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

//For getting user address
export const GETUSERADDRESS_REQUEST = 'GETUSERADDRESS_REQUEST';
export const GETUSERADDRESS_SUCCESS = 'GETUSERADDRESS_SUCCESS';

//For Adding User Address
export const ADDADDRESS_REQUEST = 'ADDADDRESS_REQUEST';
export const ADDADDRESS_SUCCESS = 'ADDADDRESS_SUCCESS';
export const ADDADDRESS_ERROR = 'ADDADDRESS_ERROR';

//For Delete User Address
export const DELADDRESS_REQUEST = 'DELADDRESS_REQUEST';
export const DELADDRESS_SUCCESS = 'DELADDRESS_SUCCESS';
export const DELADDRESS_ERROR = 'DELADDRESS_ERROR';

//For Update User Address
export const UPDATEADDRESS_REQUEST = 'UPDATEADDRESS_REQUEST';
export const UPDATEADDRESS_SUCCESS = 'UPDATEADDRESS_SUCCESS';
export const UPDATEADDRESS_ERROR = 'UPDATEADDRESS_ERROR';

//For Getting Cart Products
export const GETCARTPRODUCT_REQUEST = 'GETCARTPRODUCT_REQUEST';
export const GETCARTPRODUCT_SUCCESS = 'GETCARTPRODUCT_SUCCESS';

//For Add Cart Products
export const ADDCARTPRODUCT_REQUEST = 'ADDCARTPRODUCT_REQUEST';
export const ADDCARTPRODUCT_SUCCESS = 'ADDCARTPRODUCT_SUCCESS';
export const ADDCARTPRODUCT_ERROR = 'ADDCARTPRODUCT_ERROR';

//For Delete Cart Products
export const DELCARTPRODUCT_REQUEST = 'DELCARTPRODUCT_REQUEST';
export const DELCARTPRODUCT_SUCCESS = 'DELCARTPRODUCT_SUCCESS';
export const DELCARTPRODUCT_ERROR = 'DELCARTPRODUCT_ERROR';

//For Updating Cart Products quantity
export const UPDATEPRODUCTQUANTITY_REQUEST = 'UPDATEPRODUCTQUANTITY_REQUEST';
export const UPDATEPRODUCTQUANTITY_SUCCESS = 'UPDATEPRODUCTQUANTITY_SUCCESS';

// saving user address for delivery
export const SAVEUSERADDRESSREQUEST = 'SAVEUSERADDRESSREQUEST';

//Order Place
export const PLACEORDER_REQUEST = 'PLACEORDER_REQUEST';
export const PLACEORDER_SUCCESS = 'PLACEORDER_SUCCESS';
export const PLACEORDER_ERROR = 'PLACEORDER_ERROR';

//Get Order List
export const GETORDERLIST_REQUEST = 'GETORDERLIST_REQUEST';
export const GETORDERLIST_SUCCESS = 'GETORDERLIST_SUCCESS';

// Change Password
export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_ERROR = 'CHANGEPASSWORD_ERROR';

// Change User Profile Image
export const USERIMAGE_REQUEST = 'USERIMAGE_REQUEST';

// Filter Product category
export const FILTERCATEGORY = 'FILTERCATEGORY';

// Filter Product color
export const FILTERCOLOR = 'FILTERCOLOR';

// Filter Product rating
export const FILTERRATING = 'FILTERRATING';

// Filter Product price
export const FILTERPRICE = 'FILTERPRICE';
